#!/usr/bin/env python3
"""
watch_trade.py — standalone live trade alignment watcher
Runs forever with no Claude Code dependency.
Polls state/dashboard/log every 2s (in trade) or 10s (idle).
Logs mismatches to ~/lab_data/trade_audit_notes.md.

Usage:
    python3 watch_trade.py
    python3 watch_trade.py &   # background
"""

import csv
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

BASE        = Path(__file__).parent
STATE_FILE  = BASE / "state/vrl_v8_state.json"
DASH_FILE   = BASE / "state/vrl_dashboard.json"
LOG_FILE    = Path.home() / "logs/live/vrl_live.log"
CSV_FILE    = Path.home() / "lab_data/vrl_trade_log.csv"
AUDIT_FILE  = Path.home() / "lab_data/trade_audit_notes.md"

POLL_IDLE   = 10   # seconds when no trade
POLL_TRADE  = 2    # seconds while in trade

# ── helpers ──────────────────────────────────────────────────────────────────

def _read_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}

def _file_age(path):
    try:
        return time.time() - os.path.getmtime(path)
    except Exception:
        return 9999

def _last_tg_lines(n=80):
    try:
        result = subprocess.run(
            ["tail", "-n", str(n), str(LOG_FILE)],
            capture_output=True, text=True
        )
        return [l for l in result.stdout.splitlines() if "[TG] sent" in l]
    except Exception:
        return []

def _last_csv_row():
    try:
        with open(CSV_FILE) as f:
            rows = list(csv.DictReader(f))
        return rows[-1] if rows else {}
    except Exception:
        return {}

def _expected_sl(peak_pnl, initial_sl, entry_price, peak_ltp=None):
    if peak_pnl >= 18.0:
        p = peak_ltp if peak_ltp and peak_ltp > 0 else (entry_price + peak_pnl)
        sl = max(initial_sl, entry_price, p - 10.0)
        return round(sl, 2), "TRAIL_10"
    elif peak_pnl >= 12.0:
        sl = max(initial_sl, entry_price)
        return round(sl, 2), "BREAKEVEN"
    else:
        return round(initial_sl, 2), "INITIAL"

def _append_audit(lines):
    AUDIT_FILE.parent.mkdir(parents=True, exist_ok=True)
    write_header = not AUDIT_FILE.exists() or AUDIT_FILE.stat().st_size == 0
    with open(AUDIT_FILE, "a") as f:
        if write_header:
            f.write("# Trade Audit Notes\nAuto-generated by watch_trade.py — append-only.\n\n")
        f.write("\n".join(lines) + "\n")

def _ts():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ── alignment audit ───────────────────────────────────────────────────────────

def _audit(st, dash):
    pos     = dash.get("position", {})
    bugs    = []
    summary = []

    direction  = st.get("direction", "")
    strike     = st.get("strike", 0)
    symbol     = st.get("symbol", "")
    entry      = float(st.get("entry_price", 0))
    peak       = float(st.get("peak_pnl", 0))
    initial_sl = float(st.get("initial_sl", 0))
    tier       = st.get("active_ratchet_tier", "")
    sl         = float(st.get("active_ratchet_sl", 0))
    candles    = st.get("candles_held", 0)
    lot2f      = bool(st.get("lot2_filled", False))
    lot2c      = bool(st.get("lot2_cancelled", False))

    # ── expected SL tier from V10 formula ──
    exp_sl, exp_tier = _expected_sl(peak, initial_sl, entry)

    # ── last TG entry alert (grep for direction+strike) ──
    tg_lines = _last_tg_lines()
    tg_entry_price = None
    for line in reversed(tg_lines):
        m = re.search(r"Entry.*?(\d+\.\d+)|₹(\d+\.\d+)", line)
        if m and (str(strike) in line or direction in line):
            tg_entry_price = float(m.group(1) or m.group(2))
            break

    # ── dashboard age check ──
    age = _file_age(DASH_FILE)
    if age > 60:
        bugs.append(f"  - STALE: dashboard.json not updated for {int(age)}s")

    # ── field comparisons ──
    checks = [
        ("strike",    strike,    pos.get("strike", 0),              0),
        ("direction", direction, pos.get("direction", ""),          None),
        ("entry",     entry,     float(pos.get("entry", 0)),        0.1),
        ("peak_pnl",  round(peak,1), round(float(pos.get("peak",0)),1), 0.5),
        ("sl_price",  sl,        float(pos.get("sl", 0)),           0.1),
        ("sl_tier",   tier,      pos.get("active_ratchet_tier",""), None),
        ("candles",   candles,   pos.get("candles", 0),             0),
        ("lot2_filled",   lot2f, bool(pos.get("lot2_filled", False)),   None),
        ("lot2_cancelled",lot2c, bool(pos.get("lot2_cancelled",False)), None),
    ]

    for field, s_val, d_val, tol in checks:
        if tol is None:
            match = (str(s_val) == str(d_val))
        else:
            try:
                match = abs(float(s_val) - float(d_val)) <= tol
            except Exception:
                match = (s_val == d_val)
        status = "✓" if match else "✗ MISMATCH"
        summary.append(f"  {status:12} {field:20} state={s_val!r:20} dash={d_val!r}")
        if not match:
            bugs.append(f"  - BUG: {field} — state={s_val!r} dash={d_val!r}")

    # ── SL tier logic check ──
    if tier and tier != exp_tier:
        bugs.append(f"  - BUG: sl_tier logic — state={tier!r} expected={exp_tier!r} (peak={peak})")
    elif tier:
        summary.append(f"  {'✓':12} {'sl_tier_logic':20} state={tier!r} expected={exp_tier!r}")

    # ── TG entry price check ──
    if tg_entry_price is not None:
        diff = abs(tg_entry_price - entry)
        if diff > 0.5:
            bugs.append(f"  - BUG: entry_price — state={entry} tg_last_seen={tg_entry_price}")
        else:
            summary.append(f"  {'✓':12} {'tg_entry':20} state={entry} tg={tg_entry_price}")

    # ── lot2 mutual exclusion ──
    if lot2f and lot2c:
        bugs.append(f"  - BUG: lot2 both filled=True AND cancelled=True simultaneously")

    return summary, bugs

# ── reconcile on exit ─────────────────────────────────────────────────────────

def _reconcile(prev_st):
    row = _last_csv_row()
    if not row:
        return ["  - WARN: no CSV row found to reconcile"]

    lines = []
    entry   = float(prev_st.get("entry_price", 0))
    peak    = float(prev_st.get("peak_pnl", 0))
    strike  = prev_st.get("strike", 0)
    regime  = prev_st.get("entry_regime", "")

    csv_entry  = float(row.get("entry_price", 0))
    csv_exit   = float(row.get("exit_price", 0))
    csv_pnl    = float(row.get("pnl_pts", 0))
    csv_regime = row.get("entry_mode", "")
    csv_reason = row.get("exit_reason", "")

    exp_pnl = round(csv_exit - csv_entry, 2)

    lines.append(f"  CSV row: strike={row.get('strike')} entry={csv_entry} exit={csv_exit} pnl={csv_pnl} reason={csv_reason}")

    if abs(csv_entry - entry) > 0.5:
        lines.append(f"  - BUG: entry mismatch — state={entry} csv={csv_entry}")
    if abs(csv_pnl - exp_pnl) > 0.5:
        lines.append(f"  - BUG: pnl_pts mismatch — csv_pnl={csv_pnl} calc={exp_pnl} (exit-entry)")
    if regime and csv_regime and csv_regime not in ("V10_CE", "V10_PE"):
        lines.append(f"  - BUG: entry_mode stale — csv={csv_regime!r} (expected V10_CE/V10_PE)")
    if not lines[1:]:
        lines.append("  RECONCILE: CLEAN — all fields match")

    return lines

# ── main loop ─────────────────────────────────────────────────────────────────

def main():
    print(f"[{_ts()}] watch_trade.py started — audit log: {AUDIT_FILE}")
    prev_in_trade = False
    prev_st       = {}

    while True:
        st   = _read_json(STATE_FILE)
        dash = _read_json(DASH_FILE)

        in_trade = bool(st.get("in_trade", False))

        # ── trade just opened ──
        if in_trade and not prev_in_trade:
            direction = st.get("direction", "?")
            strike    = st.get("strike", 0)
            entry     = st.get("entry_price", 0)
            msg = f"\n## {_ts()} — ENTRY {direction} {strike} @ {entry}"
            print(msg)
            _append_audit([
                msg,
                f"  lot1_qty={st.get('lot1_qty')}  lot1_entry={st.get('lot1_entry')}",
                f"  lot2_qty={st.get('lot2_qty')}  lot2_limit={st.get('lot2_limit')}  lot2_filled={st.get('lot2_filled')}",
                f"  initial_sl={st.get('initial_sl')}  entry_regime={st.get('entry_regime')}",
            ])

        # ── in trade: run alignment audit ──
        if in_trade:
            summary, bugs = _audit(st, dash)
            peak = float(st.get("peak_pnl", 0))
            tier = st.get("active_ratchet_tier", "")
            sl   = float(st.get("active_ratchet_sl", 0))
            print(f"[{_ts()}] IN TRADE {st.get('direction')} {st.get('strike')}  "
                  f"peak={peak:+.1f}  tier={tier}  sl={sl}  "
                  f"lot2={'FILLED' if st.get('lot2_filled') else 'CANCEL' if st.get('lot2_cancelled') else 'PENDING'}")

            if bugs:
                block = [f"\n## {_ts()} — AUDIT {st.get('direction')} {st.get('strike')}"] + bugs
                _append_audit(block)
                for b in bugs:
                    print(f"  {b.strip()}")

        # ── trade just closed ──
        if prev_in_trade and not in_trade:
            msg = f"\n## {_ts()} — EXIT (reconcile)"
            print(msg)
            rec = _reconcile(prev_st)
            _append_audit([msg] + rec)
            for r in rec:
                print(r)

        # ── idle ──
        if not in_trade:
            trades = st.get("_trades_today", 0)
            pnl    = st.get("_pnl_today_pts", 0.0)
            print(f"[{_ts()}] idle — trades_today={trades}  pnl_today={pnl:+.1f}pts")

        prev_in_trade = in_trade
        prev_st       = st
        time.sleep(POLL_TRADE if in_trade else POLL_IDLE)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n[{_ts()}] watch_trade.py stopped")
        sys.exit(0)
