#!/usr/bin/env python3
"""
watch_trade.py — standalone live trade alignment watcher
Runs forever with no Claude Code dependency.
Polls state/dashboard/log every 2s (in trade) or 10s (idle).
Cross-checks state.json vs dashboard.json vs Telegram log.
Also watches the stock F&O SMI paper engine (every 15m, matching its cron):
state vs fno_tracker.csv vs smi_paper_log.csv + SL formula + freshness.
Logs mismatches to ~/lab_data/trade_audit_notes.md.

Usage:
    python3 watch_trade.py          # foreground
    python3 watch_trade.py &        # background
    nohup python3 watch_trade.py &  # persistent background
"""

import csv
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

BASE        = Path(__file__).parent
STATE_FILE  = BASE / "state/vrl_v11_state.json"
DASH_FILE   = BASE / "state/vrl_dashboard.json"
LOG_FILE    = Path.home() / "logs/live/vrl_live.log"
CSV_FILE    = Path.home() / "lab_data/vrl_trade_log.csv"
AUDIT_FILE  = Path.home() / "lab_data/trade_audit_notes.md"

POLL_IDLE   = 10   # seconds when no trade
POLL_TRADE  = 2    # seconds while in trade

# ── SMI paper engine (stock F&O) ──
SMI_STATE_FILE = BASE / "screener/smi_paper_state.json"
SMI_TRACKER    = BASE / "screener/fno_tracker.csv"
SMI_LOG_CSV    = BASE / "screener/smi_paper_log.csv"
SMI_SL_PCT     = 1.0          # stock SL = entry -/+ 1%
SMI_POLL       = 15 * 60      # engine runs on 15m cron — match its cadence
SMI_STALE_SEC  = 22 * 60      # state older than ~1.5 cron cycles during market hours
SMI_EXIT_REASONS = ("SL-HIT", "TRAIL-SMA8", "EOD-CLOSE", "EOD-LATE")

# ── helpers ──────────────────────────────────────────────────────────────────

def _read_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}

def _file_age(path):
    try:
        return time.time() - os.path.getmtime(path)
    except Exception:
        return 9999

def _tail_log(n=200):
    """Return last n lines of vrl_live.log."""
    try:
        r = subprocess.run(["tail", "-n", str(n), str(LOG_FILE)],
                           capture_output=True, text=True)
        return r.stdout.splitlines()
    except Exception:
        return []

def _tg_lines(n=200):
    """Return only [TG] sent ok lines from the last n log lines."""
    return [l for l in _tail_log(n) if "[TG] sent" in l and "sent ok" in l]

def _last_csv_row():
    try:
        with open(CSV_FILE) as f:
            rows = list(csv.DictReader(f))
        return rows[-1] if rows else {}
    except Exception:
        return {}

def _expected_sl(peak_pnl, initial_sl, entry_price):
    """V11 Golden 4-tier SL formula."""
    if peak_pnl >= 15.0:
        peak_ltp = entry_price + peak_pnl
        sl = max(initial_sl, entry_price + 9.0, peak_ltp - 10.0)
        return round(sl, 2), "TRAIL_10"
    elif peak_pnl >= 11.0:
        sl = max(initial_sl, entry_price + 4.0)
        return round(sl, 2), "LOCK_4"
    elif peak_pnl >= 9.0:
        sl = max(initial_sl, entry_price - 2.0)
        return round(sl, 2), "PROTECT"
    else:
        return round(initial_sl, 2), "INITIAL"

def _append_audit(lines):
    AUDIT_FILE.parent.mkdir(parents=True, exist_ok=True)
    write_header = not AUDIT_FILE.exists() or AUDIT_FILE.stat().st_size == 0
    with open(AUDIT_FILE, "a") as f:
        if write_header:
            f.write("# Trade Audit Notes\nAuto-generated by watch_trade.py — append-only.\n\n")
        f.write("\n".join(lines) + "\n")

def _ts():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ── TG event parser ───────────────────────────────────────────────────────────

class TGEvents:
    """
    Parse [TG] sent ok lines from the log.
    Bot logs first 60 chars of each TG message (newlines replaced with spaces).

    Known message prefixes:
      Entry   : "🟢/🔴 V11 GOLDEN ENTRY CE/PE <strike>"
      Exit    : "⚡ V11 GOLDEN EXIT CE/PE <strike>"
      SL Up   : "⚡ V11 SL UPGRADED → PROTECT/LOCK_4/TRAIL_10"
    """

    def __init__(self, lines):
        self.lines = lines  # all [TG] sent ok lines

    def _match(self, pattern):
        """Return all lines matching pattern (most-recent first)."""
        return [l for l in reversed(self.lines) if re.search(pattern, l)]

    def entry_sent(self, direction, strike):
        """Was an entry TG sent for this direction+strike?"""
        pattern = rf"V11 GOLDEN ENTRY {direction} {strike}"
        return bool(self._match(pattern))

    def exit_sent(self, direction, strike):
        """Was an exit TG sent for this direction+strike?"""
        pattern = rf"V11 GOLDEN EXIT {direction} {strike}"
        return bool(self._match(pattern))

    def sl_upgrade_sent(self, tier):
        """Was an SL upgrade TG sent for this tier today?"""
        pattern = rf"V11 SL UPGRADED.*{tier}"
        return bool(self._match(pattern))

    def exit_reason_from_tg(self, direction, strike):
        """Try to extract exit reason from exit TG line."""
        hits = self._match(rf"V11 GOLDEN EXIT {direction} {strike}")
        if not hits:
            return None
        # log line: "... sent ok — ⚡ V11 GOLDEN EXIT CE 23100 ━━━━━━━━━━━━━━━━━━━━━━━━━━━ EMERGENCY_SL ..."
        # but it's cut at 60 chars so reason may not be present
        for reason in ("EMERGENCY_SL", "PROTECT_2", "LOCK_4", "VISHAL_TRAIL", "EOD_EXIT", "MARKET_CLOSE"):
            if reason in hits[0]:
                return reason
        return "UNKNOWN"

# ── alignment audit ───────────────────────────────────────────────────────────

def _audit(st, dash, tg_events):
    pos  = dash.get("position", {})
    bugs = []
    info = []

    direction  = st.get("direction", "")
    strike     = int(st.get("strike", 0) or 0)
    entry      = float(st.get("entry_price", 0))
    peak       = float(st.get("peak_pnl", 0))
    initial_sl = float(st.get("initial_sl", 0))
    tier       = st.get("active_ratchet_tier", "")
    sl         = float(st.get("active_ratchet_sl", 0))
    candles    = int(st.get("candles_held", 0) or 0)

    # ── expected SL tier from V11 formula ──
    exp_sl, exp_tier = _expected_sl(peak, initial_sl, entry)

    # ── dashboard staleness ──
    age = _file_age(DASH_FILE)
    if age > 60:
        bugs.append(f"  - STALE: dashboard.json not updated for {int(age)}s")

    # ── state vs dashboard field checks ──
    checks = [
        ("strike",          strike,       int(pos.get("strike", 0) or 0),       0),
        ("direction",       direction,    pos.get("direction", ""),              None),
        ("entry_price",     entry,        float(pos.get("entry", 0)),            0.1),
        ("peak_pnl",        round(peak,1),round(float(pos.get("peak",0)),1),     0.5),
        ("sl_price",        sl,           float(pos.get("sl", 0)),               0.1),
        ("sl_tier",         tier,         pos.get("active_ratchet_tier",""),     None),
        ("candles_held",    candles,      int(pos.get("candles", 0) or 0),       0),
    ]

    for field, s_val, d_val, tol in checks:
        if tol is None:
            match = (str(s_val) == str(d_val))
        else:
            try:
                match = abs(float(s_val) - float(d_val)) <= tol
            except Exception:
                match = (s_val == d_val)
        mark = "✓" if match else "✗"
        info.append(f"  {mark} {field:22} state={str(s_val):18} dash={d_val!r}")
        if not match:
            bugs.append(f"  - BUG: {field} — state={s_val!r} dash={d_val!r}")

    # ── SL tier logic check ──
    if tier and tier != exp_tier:
        bugs.append(f"  - BUG: sl_tier logic — state={tier!r} expected={exp_tier!r} (peak={peak:.1f})")
    else:
        info.append(f"  ✓ {'sl_tier_logic':22} state={tier!r} expected={exp_tier!r}")

    # ── TG cross-checks ──
    # 1. Entry alert
    if not tg_events.entry_sent(direction, strike):
        bugs.append(f"  - BUG: TG entry alert NOT found for {direction} {strike}")
    else:
        info.append(f"  ✓ {'tg_entry_alert':22} found for {direction} {strike}")

    # 2. SL tier upgrade alerts
    if tier in ("PROTECT", "LOCK_4", "TRAIL_10"):
        if not tg_events.sl_upgrade_sent(tier):
            bugs.append(f"  - BUG: TG SL upgrade alert NOT found for {tier} (state shows {tier})")
        else:
            info.append(f"  ✓ {'tg_sl_upgrade':22} found for {tier}")

    return info, bugs

# ── reconcile on exit ─────────────────────────────────────────────────────────

def _reconcile(prev_st, tg_events):
    row = _last_csv_row()
    lines = []

    direction = prev_st.get("direction", "")
    strike    = int(prev_st.get("strike", 0) or 0)
    entry     = float(prev_st.get("entry_price", 0))
    peak      = float(prev_st.get("peak_pnl", 0))

    if not row:
        lines.append("  - WARN: no CSV row found to reconcile")
    else:
        csv_entry  = float(row.get("entry_price", 0))
        csv_exit   = float(row.get("exit_price", 0))
        csv_pnl    = float(row.get("pnl_pts", 0))
        csv_regime = row.get("entry_mode", "")
        csv_reason = row.get("exit_reason", "")
        exp_pnl    = round(csv_exit - csv_entry, 2)

        lines.append(f"  CSV: strike={row.get('strike')} entry={csv_entry} "
                     f"exit={csv_exit} pnl={csv_pnl} reason={csv_reason} mode={csv_regime}")

        if abs(csv_entry - entry) > 0.5:
            lines.append(f"  - BUG: entry mismatch — state={entry} csv={csv_entry}")
        if abs(csv_pnl - exp_pnl) > 0.5:
            lines.append(f"  - BUG: pnl_pts mismatch — csv={csv_pnl} calc={exp_pnl} (exit-entry)")
        if csv_regime and csv_regime not in ("V11_CE", "V11_PE"):
            lines.append(f"  - BUG: entry_mode stale — csv={csv_regime!r} (expected V11_CE or V11_PE)")

    # TG exit alert check
    if not tg_events.exit_sent(direction, strike):
        lines.append(f"  - BUG: TG exit alert NOT found for {direction} {strike}")
    else:
        tg_reason = tg_events.exit_reason_from_tg(direction, strike)
        csv_reason_check = row.get("exit_reason", "") if row else ""
        lines.append(f"  ✓ TG exit alert found — tg_reason={tg_reason!r} csv_reason={csv_reason_check!r}")

    if not [l for l in lines if "BUG" in l]:
        lines.append("  RECONCILE: CLEAN — all fields match")

    return lines

# ── SMI paper engine watcher ─────────────────────────────────────────────────

def _smi_market_hours():
    now = datetime.now()
    return now.weekday() < 5 and "09:47" <= now.strftime("%H:%M") <= "15:31"

def _smi_tracker_rows():
    """fno_tracker.csv rows with structure=SMI, keyed by option_symbol."""
    try:
        with open(SMI_TRACKER) as f:
            return {r["option_symbol"]: r for r in csv.DictReader(f)
                    if r.get("structure") == "SMI"}
    except Exception:
        return {}

def _smi_log_rows():
    try:
        with open(SMI_LOG_CSV) as f:
            return list(csv.DictReader(f))
    except Exception:
        return []

def _smi_audit(open_trades):
    """Audit each open SMI trade. Returns (info, bugs)."""
    info, bugs = [], []
    tracker = _smi_tracker_rows()

    if _smi_market_hours():
        age = _file_age(SMI_STATE_FILE)
        if age > SMI_STALE_SEC:
            bugs.append(f"  - STALE: smi_paper_state.json not updated for {int(age // 60)}m "
                        f"(cron runs every 15m — engine may be down)")

    for sym, tr in open_trades.items():
        sgn    = 1 if tr.get("direction") == "CE" else -1
        entry  = float(tr.get("stock_entry", 0))
        sl     = float(tr.get("sl_price", 0))
        peak   = float(tr.get("peak", 0))
        armed  = bool(tr.get("armed", False))
        opt    = tr.get("option_symbol", "")

        # SL formula: stock entry -/+ 1%
        exp_sl = round(entry * (1 - sgn * SMI_SL_PCT / 100), 2)
        if abs(sl - exp_sl) > 0.05:
            bugs.append(f"  - BUG: {sym} sl_price={sl} expected={exp_sl} (entry {entry} ∓1%)")
        else:
            info.append(f"  ✓ {sym:14} {tr.get('direction')} entry={entry} sl={sl} "
                        f"peak={peak:+.2f}% armed={armed}")

        # trail must be armed once peak >= +1.5%
        if peak >= 1.5 and not armed:
            bugs.append(f"  - BUG: {sym} peak={peak:+.2f}% >= +1.5% but trail not armed")

        # tracker row must exist and be OPEN
        row = tracker.get(opt)
        if not row:
            bugs.append(f"  - BUG: {sym} open in state but no SMI row in fno_tracker.csv ({opt})")
        elif not str(row.get("status", "")).startswith("OPEN"):
            bugs.append(f"  - BUG: {sym} open in state but tracker status={row.get('status')!r}")

    return info, bugs

def _smi_reconcile(closed_trades):
    """Symbols that left open_trades — verify they landed in smi_paper_log.csv."""
    lines = []
    log_rows = _smi_log_rows()
    tracker = _smi_tracker_rows()

    for sym, tr in closed_trades.items():
        hits = [r for r in log_rows
                if r.get("symbol") == sym and r.get("entry_time") == tr.get("entry_time")]
        if not hits:
            lines.append(f"  - BUG: {sym} left state but no row in smi_paper_log.csv")
            continue
        row = hits[-1]
        reason = row.get("exit_reason", "")
        lines.append(f"  {sym}: stock {float(row.get('pnl_pct_stock', 0)):+.2f}% "
                     f"₹{float(row.get('pnl_rs', 0)):+,.0f} reason={reason} "
                     f"opt {row.get('entry_premium')}→{row.get('exit_premium')}")
        if reason not in SMI_EXIT_REASONS:
            lines.append(f"  - BUG: {sym} unknown exit_reason={reason!r}")
        try:
            exp_rs = (float(row["exit_premium"]) - float(row["entry_premium"])) \
                     * float(row["lot_size"])
            if abs(float(row["pnl_rs"]) - exp_rs) > 1.0:
                lines.append(f"  - BUG: {sym} pnl_rs={row['pnl_rs']} calc={exp_rs:.0f}")
        except Exception:
            lines.append(f"  - WARN: {sym} could not verify pnl_rs from log row")
        trow = tracker.get(tr.get("option_symbol", ""))
        if trow and str(trow.get("status", "")).startswith("OPEN"):
            lines.append(f"  - BUG: {sym} closed in log but tracker still {trow.get('status')!r}")

    if not [l for l in lines if "BUG" in l]:
        lines.append("  SMI RECONCILE: CLEAN")
    return lines

# ── main loop ─────────────────────────────────────────────────────────────────

def main():
    print(f"[{_ts()}] watch_trade.py started — audit: {AUDIT_FILE}")
    prev_in_trade = False
    prev_st       = {}
    smi_last_poll = 0.0
    smi_prev_open = None   # None = not read yet (avoid false EXITs on startup)

    while True:
        st   = _read_json(STATE_FILE)
        dash = _read_json(DASH_FILE)
        tg   = TGEvents(_tg_lines(300))

        in_trade = bool(st.get("in_trade", False))

        # ── trade just opened ──
        if in_trade and not prev_in_trade:
            direction = st.get("direction", "?")
            strike    = st.get("strike", 0)
            entry     = st.get("entry_price", 0)
            block = [
                f"\n## {_ts()} — ENTRY {direction} {strike} @ {entry}",
                f"  qty={st.get('qty')}",
                f"  initial_sl={st.get('initial_sl')}  entry_regime={st.get('entry_regime')}",
                f"  tg_entry_alert={'FOUND' if tg.entry_sent(direction, strike) else 'MISSING ← BUG'}",
            ]
            print("\n".join(block))
            _append_audit(block)

        # ── in trade: alignment audit ──
        if in_trade:
            info, bugs = _audit(st, dash, tg)
            peak = float(st.get("peak_pnl", 0))
            tier = st.get("active_ratchet_tier", "")
            sl   = float(st.get("active_ratchet_sl", 0))
            print(f"[{_ts()}] {st.get('direction')} {st.get('strike')}  "
                  f"peak={peak:+.1f}  tier={tier}  sl={sl:.1f}"
                  + (f"  ⚠ {len(bugs)} BUG(s)" if bugs else "  ✓"))

            if bugs:
                block = [f"\n## {_ts()} — AUDIT {st.get('direction')} {st.get('strike')}"] + bugs
                _append_audit(block)
                for b in bugs:
                    print(f"  {b.strip()}")

        # ── trade just closed ──
        if prev_in_trade and not in_trade:
            msg = f"\n## {_ts()} — EXIT (reconcile)"
            print(msg)
            rec = _reconcile(prev_st, TGEvents(_tg_lines(300)))
            _append_audit([msg] + rec)
            for r in rec:
                print(r)

        # ── idle ──
        if not in_trade:
            trades = st.get("_trades_today", 0)
            pnl    = st.get("_pnl_today_pts", 0.0)
            print(f"[{_ts()}] idle — trades={trades}  pnl={pnl:+.1f}pts")

        # ── SMI paper engine (stock F&O) — every SMI_POLL seconds ──
        if time.time() - smi_last_poll >= SMI_POLL:
            smi_last_poll = time.time()
            smi_open = _read_json(SMI_STATE_FILE).get("open_trades", {})

            if smi_prev_open is not None:
                # new entries
                for sym in smi_open.keys() - smi_prev_open.keys():
                    tr = smi_open[sym]
                    block = [
                        f"\n## {_ts()} — SMI ENTRY {sym} {tr.get('direction')} "
                        f"@ {tr.get('stock_entry')}",
                        f"  {tr.get('option_symbol')} prem={tr.get('entry_premium')} "
                        f"sl={tr.get('sl_price')} {tr.get('conviction', '')}",
                    ]
                    print("\n".join(block))
                    _append_audit(block)
                # exits — reconcile against smi_paper_log.csv
                closed = {s: smi_prev_open[s]
                          for s in smi_prev_open.keys() - smi_open.keys()}
                if closed:
                    msg = f"\n## {_ts()} — SMI EXIT ({', '.join(closed)})"
                    rec = _smi_reconcile(closed)
                    print(msg)
                    _append_audit([msg] + rec)
                    for r in rec:
                        print(r)

            info, bugs = _smi_audit(smi_open)
            if smi_open:
                print(f"[{_ts()}] SMI — {len(smi_open)} open: "
                      + ", ".join(f"{s} {t.get('direction')} {float(t.get('peak', 0)):+.1f}%"
                                  for s, t in smi_open.items())
                      + (f"  ⚠ {len(bugs)} BUG(s)" if bugs else "  ✓"))
            if bugs:
                block = [f"\n## {_ts()} — SMI AUDIT"] + bugs
                _append_audit(block)
                for b in bugs:
                    print(f"  {b.strip()}")
            smi_prev_open = smi_open

        prev_in_trade = in_trade
        prev_st       = st
        time.sleep(POLL_TRADE if in_trade else POLL_IDLE)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n[{_ts()}] watch_trade.py stopped")
        sys.exit(0)
